#
# Makefile for stand-alone compass input device drivers
#

obj-$(CONFIG_INV_YAS53X) += inv-yas53x.o
inv-yas53x-objs += yas53x_input.o

obj-$(CONFIG_INV_AK89XX) += inv-ak89xx.o
inv-ak89xx-objs += ak89xx_input.o

